version: "3.9"

services:
  storybook-lesson:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
